---@meta
---@diagnostic disable: missing-fields
-- Type definitions for hackers-browser's config.lua, for lua-language-server.
-- Generated by `hackers-browser --lua-types`; do not edit.

---@alias hb.Mode "normal"|"insert"|"command"|"passthrough"|"hint"
---@alias hb.SettingName "aliases"|"hints.chars"|"hints.uppercase"|"input.forward_unbound_keys"|"input.insert_mode.auto_enter"|"input.insert_mode.auto_leave"|"input.insert_mode.leave_on_load"|"messages.timeout"|"tabs.last_close"|"tabs.mode_on_change"|"tabs.new_position.related"|"tabs.new_position.unrelated"|"url.default_page"|"url.searchengines"|"url.start_pages"

---@class hb
---@field platform "linux"|"macos"|"windows"
---@field version string
---@field config_dir string
---@field data_dir string
hb = {}

---Set an option; `c.name = value` does the same.
---@param name hb.SettingName
---@param value any
function hb.set(name, value) end

---Get an option's current value.
---@param name hb.SettingName
---@return any
function hb.get(name) end

---Bind keys (qutebrowser notation, e.g. "<Ctrl-x>" or "gg") to a command.
---@param keys string
---@param command string
---@param mode? hb.Mode defaults to "normal"
function hb.bind(keys, command, mode) end

---Remove a binding.
---@param keys string
---@param mode? hb.Mode defaults to "normal"
function hb.unbind(keys, mode) end

---@class hb.c
---@field aliases table<string, string> Command aliases: name → command
---@field hints hb.c.hints
---@field input hb.c.input
---@field messages hb.c.messages
---@field tabs hb.c.tabs
---@field url hb.c.url

---@class hb.c.hints
---@field chars string Characters used for hint labels
---@field uppercase boolean Show hint labels in upper case

---@class hb.c.input
---@field forward_unbound_keys "all"|"auto"|"none" Pass unbound keys to the page in normal mode (auto: all but plain letters and digits)
---@field insert_mode hb.c.input.insert_mode

---@class hb.c.input.insert_mode
---@field auto_enter boolean Enter insert mode when an editable element gets focus
---@field auto_leave boolean Leave insert mode when focus leaves an editable element
---@field leave_on_load boolean Leave insert mode when a new page starts loading

---@class hb.c.messages
---@field timeout integer Milliseconds before a status bar message clears (0 keeps it)

---@class hb.c.tabs
---@field last_close "ignore"|"blank"|"startpage"|"default-page"|"close" What closing the last tab does
---@field mode_on_change "normal"|"persist" Mode after switching tabs: back to normal, or keep insert/passthrough
---@field new_position hb.c.tabs.new_position

---@class hb.c.tabs.new_position
---@field related "prev"|"next"|"first"|"last" Where tabs opened from a page go (popups, hints)
---@field unrelated "prev"|"next"|"first"|"last" Where other new tabs go (:open -t)

---@class hb.c.url
---@field default_page string Page for :open without a URL
---@field searchengines table<string, string> Search engines; ':open g rust' uses the 'g' entry, anything else DEFAULT
---@field start_pages string[] Pages opened at startup when no URL is given

---@type hb.c
c = {}
