---@meta
---@diagnostic disable: missing-fields
-- Type definitions for hackers-browser's config.lua, for lua-language-server.
-- Generated by `hackers-browser --lua-types`; do not edit.

---@alias hb.Mode "normal"|"insert"|"command"|"passthrough"|"hint"|"prompt"|"yesno"
---@alias hb.SettingName "aliases"|"auto_save.session"|"completion.web_history.max_items"|"content.blocking.adblock.lists"|"content.blocking.enabled"|"content.blocking.whitelist"|"content.desktop_capture"|"content.geolocation"|"content.media.audio_capture"|"content.media.video_capture"|"content.notifications.enabled"|"downloads.location.directory"|"downloads.location.prompt"|"hints.chars"|"hints.uppercase"|"input.forward_unbound_keys"|"input.insert_mode.auto_enter"|"input.insert_mode.auto_leave"|"input.insert_mode.leave_on_load"|"messages.timeout"|"new_instance_open_target"|"tabs.favicons.show"|"tabs.last_close"|"tabs.mode_on_change"|"tabs.mousewheel_switching"|"tabs.new_position.related"|"tabs.new_position.unrelated"|"tabs.pinned.frozen"|"tabs.pinned.shrink"|"url.default_page"|"url.searchengines"|"url.start_pages"|"window.title_format"

---@class hb
---@field platform "linux"|"macos"|"windows"
---@field version string
---@field config_dir string
---@field data_dir string
hb = {}

---Set an option; `c.name = value` does the same.
---@param name hb.SettingName
---@param value any
function hb.set(name, value) end

---Get an option's current value.
---@param name hb.SettingName
---@return any
function hb.get(name) end

---Bind keys (qutebrowser notation, e.g. "<Ctrl-x>" or "gg") to a command.
---@param keys string
---@param command string
---@param mode? hb.Mode defaults to "normal"
function hb.bind(keys, command, mode) end

---Remove a binding.
---@param keys string
---@param mode? hb.Mode defaults to "normal"
function hb.unbind(keys, mode) end

---@class hb.c
---@field aliases table<string, string> Command aliases: name → command
---@field auto_save hb.c.auto_save
---@field completion hb.c.completion
---@field content hb.c.content
---@field downloads hb.c.downloads
---@field hints hb.c.hints
---@field input hb.c.input
---@field messages hb.c.messages
---@field new_instance_open_target "tab"|"tab-bg"|"window" Where URLs from a second hackers-browser invocation open
---@field tabs hb.c.tabs
---@field url hb.c.url
---@field window hb.c.window

---@class hb.c.auto_save
---@field session boolean Save the open tabs as the 'default' session on quit, and restore them at startup

---@class hb.c.completion
---@field web_history hb.c.completion.web_history

---@class hb.c.completion.web_history
---@field max_items integer How many history entries :open completion shows (0 turns history completion off)

---@class hb.c.content
---@field blocking hb.c.content.blocking
---@field desktop_capture "ask"|"true"|"false" Let sites capture your screen or desktop audio: ask, true or false
---@field geolocation "ask"|"true"|"false" Let sites know your location: ask, true or false
---@field media hb.c.content.media
---@field notifications hb.c.content.notifications

---@class hb.c.content.blocking
---@field adblock hb.c.content.blocking.adblock
---@field enabled boolean Block ads and trackers with the filter lists from content.blocking.adblock.lists
---@field whitelist string[] Sites where nothing is blocked, as host names; a host also covers its subdomains

---@class hb.c.content.blocking.adblock
---@field lists string[] Adblock Plus filter lists that :adblock-update downloads (https://, or file:// for local lists)

---@class hb.c.content.media
---@field audio_capture "ask"|"true"|"false" Let sites use your microphone: ask, true or false
---@field video_capture "ask"|"true"|"false" Let sites use your camera: ask, true or false

---@class hb.c.content.notifications
---@field enabled "ask"|"true"|"false" Let sites show notifications: ask, true or false

---@class hb.c.downloads
---@field location hb.c.downloads.location

---@class hb.c.downloads.location
---@field directory string Where downloads go; empty means the system Downloads folder
---@field prompt boolean Ask where to save each download (false saves straight to the directory)

---@class hb.c.hints
---@field chars string Characters used for hint labels
---@field uppercase boolean Show hint labels in upper case

---@class hb.c.input
---@field forward_unbound_keys "all"|"auto"|"none" Pass unbound keys to the page in normal mode (auto: all but plain letters and digits)
---@field insert_mode hb.c.input.insert_mode

---@class hb.c.input.insert_mode
---@field auto_enter boolean Enter insert mode when an editable element gets focus
---@field auto_leave boolean Leave insert mode when focus leaves an editable element
---@field leave_on_load boolean Leave insert mode when a new page starts loading

---@class hb.c.messages
---@field timeout integer Milliseconds before a status bar message clears (0 keeps it)

---@class hb.c.tabs
---@field favicons hb.c.tabs.favicons
---@field last_close "ignore"|"blank"|"startpage"|"default-page"|"close" What closing the last tab does
---@field mode_on_change "normal"|"persist" Mode after switching tabs: back to normal, or keep insert/passthrough
---@field mousewheel_switching boolean Switch tabs with the mouse wheel over the tab bar
---@field new_position hb.c.tabs.new_position
---@field pinned hb.c.tabs.pinned

---@class hb.c.tabs.favicons
---@field show "always"|"never"|"pinned" Show site icons in the tab bar: always, never, or only on pinned tabs

---@class hb.c.tabs.new_position
---@field related "prev"|"next"|"first"|"last" Where tabs opened from a page go (popups, hints)
---@field unrelated "prev"|"next"|"first"|"last" Where other new tabs go (:open -t)

---@class hb.c.tabs.pinned
---@field frozen boolean Keep pinned tabs on their page: :open in a pinned tab opens a new tab
---@field shrink boolean Shrink pinned tabs to their icon and number

---@class hb.c.url
---@field default_page string Page for :open without a URL
---@field searchengines table<string, string> Search engines; ':open g rust' uses the 'g' entry, anything else DEFAULT
---@field start_pages string[] Pages opened at startup when no URL is given

---@class hb.c.window
---@field title_format string Window title; fields: {current_title}, {title_sep}, {current_url}, {host}, {mode}

---@type hb.c
c = {}
