---@meta
---@diagnostic disable: missing-fields
-- Type definitions for hackers-browser's config.lua, for lua-language-server.
-- Generated by `hackers-browser --lua-types`; do not edit.

---@alias hb.Mode "normal"|"insert"|"command"|"passthrough"|"hint"|"prompt"|"yesno"|"set_mark"|"jump_mark"|"record_macro"|"run_macro"|"caret"
---@alias hb.SettingName "aliases"|"auto_save.interval"|"auto_save.session"|"colors.webpage.darkmode.enabled"|"colors.webpage.preferred_color_scheme"|"completion.web_history.max_items"|"content.blocking.adblock.lists"|"content.blocking.enabled"|"content.blocking.whitelist"|"content.desktop_capture"|"content.geolocation"|"content.media.audio_capture"|"content.media.video_capture"|"content.notifications.enabled"|"content.tls.certificate_errors"|"content.widevine"|"downloads.location.directory"|"downloads.location.prompt"|"editor.command"|"hints.chars"|"hints.mode"|"hints.uppercase"|"input.forward_unbound_keys"|"input.insert_mode.auto_enter"|"input.insert_mode.auto_leave"|"input.insert_mode.leave_on_load"|"messages.timeout"|"new_instance_open_target"|"search.ignore_case"|"search.incremental"|"spellcheck.languages"|"tabs.favicons.show"|"tabs.last_close"|"tabs.mode_on_change"|"tabs.mousewheel_switching"|"tabs.new_position.related"|"tabs.new_position.unrelated"|"tabs.pinned.frozen"|"tabs.pinned.shrink"|"url.default_page"|"url.searchengines"|"url.start_pages"|"window.title_format"

---@class hb
---@field platform "linux"|"macos"|"windows"
---@field version string
---@field config_dir string
---@field data_dir string
hb = {}

---Set an option; `c.name = value` does the same. With `pattern` (e.g.
---`"*.example.com"` or `"https://meet.example.com"`), only for matching pages;
---this works for the content.* permission settings and content.blocking.enabled.
---@param name hb.SettingName
---@param value any
---@param pattern? string
function hb.set(name, value, pattern) end

---Get an option's current value.
---@param name hb.SettingName
---@return any
function hb.get(name) end

---Bind keys (qutebrowser notation, e.g. "<Ctrl-x>" or "gg") to a command,
---or to a Lua function that runs when they're pressed.
---@param keys string
---@param command string|fun()
---@param mode? hb.Mode defaults to "normal"
function hb.bind(keys, command, mode) end

---Remove a binding.
---@param keys string
---@param mode? hb.Mode defaults to "normal"
function hb.unbind(keys, mode) end

---Define a command, e.g. `:wiki rust`; `fn` gets the rest of the line.
---@param name string letters, digits, `-` and `_`
---@param fn fun(args: string)
---@param description? string shown in completion
function hb.command(name, fn, description) end

---Run `fn` on an event: "load_finished" and "url_changed" (`e.url`),
---"tab_opened" (`e.url`) or "mode_changed" (`e.from`, `e.to`).
---@param event "load_finished"|"url_changed"|"tab_opened"|"mode_changed"
---@param fn fun(e: table)
function hb.on(event, fn) end

---The current page's URL (in callbacks).
---@return string
function hb.url() end

---The current page's title (in callbacks).
---@return string
function hb.title() end

---The current mode, e.g. "normal" (in callbacks).
---@return string
function hb.mode() end

---The current window's tabs, in order (in callbacks).
---@return { index: integer, title: string, url: string, current: boolean, pinned: boolean }[]
function hb.tabs() end

---The count typed before the key, if any (in callbacks).
---@return integer?
function hb.count() end

---Run a command line, e.g. `hb.run("tab-close")` (in callbacks).
---@param line string
function hb.run(line) end

---Open a URL (in callbacks).
---@param url string
---@param target? "current"|"tab"|"tab-bg"|"window"|"private"
function hb.open(url, target) end

---Show a message in the status bar (in callbacks).
---@param text string
---@param level? "info"|"error"
function hb.message(text, level) end

---@class hb.c
---@field aliases table<string, string> Command aliases: name → command
---@field auto_save hb.c.auto_save
---@field colors hb.c.colors
---@field completion hb.c.completion
---@field content hb.c.content
---@field downloads hb.c.downloads
---@field editor hb.c.editor
---@field hints hb.c.hints
---@field input hb.c.input
---@field messages hb.c.messages
---@field new_instance_open_target "tab"|"tab-bg"|"window" Where URLs from a second hackers-browser invocation open
---@field search hb.c.search
---@field spellcheck hb.c.spellcheck
---@field tabs hb.c.tabs
---@field url hb.c.url
---@field window hb.c.window

---@class hb.c.auto_save
---@field interval integer Milliseconds between crash-recovery saves of the open tabs (0 turns them off)
---@field session boolean Save the open tabs as the 'default' session on quit, and restore them at startup

---@class hb.c.colors
---@field webpage hb.c.colors.webpage

---@class hb.c.colors.webpage
---@field darkmode hb.c.colors.webpage.darkmode
---@field preferred_color_scheme "auto"|"light"|"dark" The color scheme pages see in prefers-color-scheme: auto follows the system

---@class hb.c.colors.webpage.darkmode
---@field enabled boolean Render light pages dark with Chromium's automatic dark mode (takes effect after a restart)

---@class hb.c.completion
---@field web_history hb.c.completion.web_history

---@class hb.c.completion.web_history
---@field max_items integer How many history entries :open completion shows (0 turns history completion off)

---@class hb.c.content
---@field blocking hb.c.content.blocking
---@field desktop_capture "ask"|"true"|"false" Let sites capture your screen or desktop audio: ask, true or false
---@field geolocation "ask"|"true"|"false" Let sites know your location: ask, true or false
---@field media hb.c.content.media
---@field notifications hb.c.content.notifications
---@field tls hb.c.content.tls
---@field widevine boolean Allow Widevine DRM: Chromium downloads Google's CDM once (takes effect after a restart)

---@class hb.c.content.blocking
---@field adblock hb.c.content.blocking.adblock
---@field enabled boolean Block ads and trackers with the filter lists from content.blocking.adblock.lists
---@field whitelist string[] Sites where nothing is blocked, as host names; a host also covers its subdomains

---@class hb.c.content.blocking.adblock
---@field lists string[] Adblock Plus filter lists that :adblock-update downloads (https://, or file:// for local lists)

---@class hb.c.content.media
---@field audio_capture "ask"|"true"|"false" Let sites use your microphone: ask, true or false
---@field video_capture "ask"|"true"|"false" Let sites use your camera: ask, true or false

---@class hb.c.content.notifications
---@field enabled "ask"|"true"|"false" Let sites show notifications: ask, true or false

---@class hb.c.content.tls
---@field certificate_errors "ask"|"block"|"load-insecurely" Pages whose TLS certificate isn't trusted: ask, block, or load-insecurely

---@class hb.c.downloads
---@field location hb.c.downloads.location

---@class hb.c.downloads.location
---@field directory string Where downloads go; empty means the system Downloads folder
---@field prompt boolean Ask where to save each download (false saves straight to the directory)

---@class hb.c.editor
---@field command string[] Editor for :open-editor; fields: {file}, {line}, {column}, {line0}, {column0}

---@class hb.c.hints
---@field chars string Characters used for hint labels
---@field mode "letter"|"number" letter: labels from hints.chars; number: numbered labels, and typing letters filters by text
---@field uppercase boolean Show hint labels in upper case

---@class hb.c.input
---@field forward_unbound_keys "all"|"auto"|"none" Pass unbound keys to the page in normal mode (auto: all but plain letters and digits)
---@field insert_mode hb.c.input.insert_mode

---@class hb.c.input.insert_mode
---@field auto_enter boolean Enter insert mode when an editable element gets focus
---@field auto_leave boolean Leave insert mode when focus leaves an editable element
---@field leave_on_load boolean Leave insert mode when a new page starts loading

---@class hb.c.messages
---@field timeout integer Milliseconds before a status bar message clears (0 keeps it)

---@class hb.c.search
---@field ignore_case "smart"|"always"|"never" Case in searches: smart ignores it unless the text has a capital, always, or never
---@field incremental boolean Search while typing after / or ?

---@class hb.c.spellcheck
---@field languages string[] Spell-check languages such as en-US (empty: off); Chromium downloads each dictionary from Google once

---@class hb.c.tabs
---@field favicons hb.c.tabs.favicons
---@field last_close "ignore"|"blank"|"startpage"|"default-page"|"close" What closing the last tab does
---@field mode_on_change "normal"|"persist"|"restore" Mode after switching tabs: normal, persist (keep insert/passthrough), or restore (the mode the tab was left in)
---@field mousewheel_switching boolean Switch tabs with the mouse wheel over the tab bar
---@field new_position hb.c.tabs.new_position
---@field pinned hb.c.tabs.pinned

---@class hb.c.tabs.favicons
---@field show "always"|"never"|"pinned" Show site icons in the tab bar: always, never, or only on pinned tabs

---@class hb.c.tabs.new_position
---@field related "prev"|"next"|"first"|"last" Where tabs opened from a page go (popups, hints)
---@field unrelated "prev"|"next"|"first"|"last" Where other new tabs go (:open -t)

---@class hb.c.tabs.pinned
---@field frozen boolean Keep pinned tabs on their page: :open in a pinned tab opens a new tab
---@field shrink boolean Shrink pinned tabs to their icon and number

---@class hb.c.url
---@field default_page string Page for :open without a URL
---@field searchengines table<string, string> Search engines; ':open g rust' uses the 'g' entry, anything else DEFAULT
---@field start_pages string[] Pages opened at startup when no URL is given

---@class hb.c.window
---@field title_format string Window title; fields: {current_title}, {title_sep}, {current_url}, {host}, {mode}

---@type hb.c
c = {}
