---@meta
---@diagnostic disable: missing-fields
-- Type definitions for riptide's config.lua, for lua-language-server.
-- Generated by `riptide --lua-types`; do not edit.

---@alias rt.Mode "normal"|"insert"|"command"|"passthrough"|"hint"|"prompt"|"yesno"|"set_mark"|"jump_mark"|"record_macro"|"run_macro"|"caret"
---@alias rt.SettingName "aliases"|"auto_save.interval"|"auto_save.session"|"colors.webpage.darkmode.enabled"|"colors.webpage.preferred_color_scheme"|"completion.web_history.max_items"|"content.blocking.adblock.lists"|"content.blocking.enabled"|"content.blocking.whitelist"|"content.desktop_capture"|"content.geolocation"|"content.media.audio_capture"|"content.media.video_capture"|"content.notifications.enabled"|"content.tls.certificate_errors"|"content.widevine"|"downloads.location.directory"|"downloads.location.prompt"|"editor.command"|"hints.chars"|"hints.mode"|"hints.uppercase"|"input.forward_unbound_keys"|"input.insert_mode.auto_enter"|"input.insert_mode.auto_leave"|"input.insert_mode.leave_on_load"|"messages.timeout"|"new_instance_open_target"|"search.ignore_case"|"search.incremental"|"spellcheck.languages"|"statusbar.position"|"statusbar.show"|"statusbar.widgets"|"tabs.favicons.show"|"tabs.last_close"|"tabs.mode_on_change"|"tabs.mousewheel_switching"|"tabs.new_position.related"|"tabs.new_position.unrelated"|"tabs.pinned.frozen"|"tabs.pinned.shrink"|"tabs.position"|"tabs.show"|"tabs.show_switching_delay"|"tabs.width"|"url.default_page"|"url.searchengines"|"url.start_pages"|"window.title_format"|"zoom.default"

---@class rt
---@field platform "linux"|"macos"|"windows"
---@field version string
---@field config_dir string
---@field data_dir string
rt = {}

---@deprecated `hb` is the old name of `rt`.
hb = rt

---Set an option; `c.name = value` does the same. With `pattern` (e.g.
---`"*.example.com"` or `"https://meet.example.com"`), only for matching pages;
---this works for the content.* permission settings and content.blocking.enabled.
---@param name rt.SettingName
---@param value any
---@param pattern? string
function rt.set(name, value, pattern) end

---Get an option's current value.
---@param name rt.SettingName
---@return any
function rt.get(name) end

---Bind keys (qutebrowser notation, e.g. "<Ctrl-x>" or "gg") to a command,
---or to a Lua function that runs when they're pressed.
---@param keys string
---@param command string|fun()
---@param mode? rt.Mode defaults to "normal"
function rt.bind(keys, command, mode) end

---Remove a binding.
---@param keys string
---@param mode? rt.Mode defaults to "normal"
function rt.unbind(keys, mode) end

---Define a command, e.g. `:wiki rust`; `fn` gets the rest of the line.
---@param name string letters, digits, `-` and `_`
---@param fn fun(args: string)
---@param description? string shown in completion
function rt.command(name, fn, description) end

---Run `fn` on an event: "load_finished" and "url_changed" (`e.url`),
---"tab_opened" (`e.url`) or "mode_changed" (`e.from`, `e.to`).
---@param event "load_finished"|"url_changed"|"tab_opened"|"mode_changed"
---@param fn fun(e: table)
function rt.on(event, fn) end

---The current page's URL (in callbacks).
---@return string
function rt.url() end

---The current page's title (in callbacks).
---@return string
function rt.title() end

---The current mode, e.g. "normal" (in callbacks).
---@return string
function rt.mode() end

---The current window's tabs, in order (in callbacks).
---@return { index: integer, title: string, url: string, current: boolean, pinned: boolean }[]
function rt.tabs() end

---The count typed before the key, if any (in callbacks).
---@return integer?
function rt.count() end

---Run a command line, e.g. `rt.run("tab-close")` (in callbacks).
---@param line string
function rt.run(line) end

---Open a URL (in callbacks).
---@param url string
---@param target? "current"|"tab"|"tab-bg"|"window"|"private"
function rt.open(url, target) end

---Show a message in the status bar (in callbacks).
---@param text string
---@param level? "info"|"error"
function rt.message(text, level) end

---@class rt.c
---@field aliases table<string, string> Command aliases: name → command
---@field auto_save rt.c.auto_save
---@field colors rt.c.colors
---@field completion rt.c.completion
---@field content rt.c.content
---@field downloads rt.c.downloads
---@field editor rt.c.editor
---@field hints rt.c.hints
---@field input rt.c.input
---@field messages rt.c.messages
---@field new_instance_open_target "tab"|"tab-bg"|"window" Where URLs from a second riptide invocation open
---@field search rt.c.search
---@field spellcheck rt.c.spellcheck
---@field statusbar rt.c.statusbar
---@field tabs rt.c.tabs
---@field url rt.c.url
---@field window rt.c.window
---@field zoom rt.c.zoom

---@class rt.c.auto_save
---@field interval integer Milliseconds between crash-recovery saves of the open tabs (0 turns them off)
---@field session boolean Save the open tabs as the 'default' session on quit, and restore them at startup

---@class rt.c.colors
---@field webpage rt.c.colors.webpage

---@class rt.c.colors.webpage
---@field darkmode rt.c.colors.webpage.darkmode
---@field preferred_color_scheme "auto"|"light"|"dark" The color scheme pages see in prefers-color-scheme: auto follows the system

---@class rt.c.colors.webpage.darkmode
---@field enabled boolean Render light pages dark with Chromium's automatic dark mode (takes effect after a restart)

---@class rt.c.completion
---@field web_history rt.c.completion.web_history

---@class rt.c.completion.web_history
---@field max_items integer How many history entries :open completion shows (0 turns history completion off)

---@class rt.c.content
---@field blocking rt.c.content.blocking
---@field desktop_capture "ask"|"true"|"false" Let sites capture your screen or desktop audio: ask, true or false
---@field geolocation "ask"|"true"|"false" Let sites know your location: ask, true or false
---@field media rt.c.content.media
---@field notifications rt.c.content.notifications
---@field tls rt.c.content.tls
---@field widevine boolean Allow Widevine DRM: Chromium downloads Google's CDM once (takes effect after a restart)

---@class rt.c.content.blocking
---@field adblock rt.c.content.blocking.adblock
---@field enabled boolean Block ads and trackers with the filter lists from content.blocking.adblock.lists
---@field whitelist string[] Sites where nothing is blocked, as host names; a host also covers its subdomains

---@class rt.c.content.blocking.adblock
---@field lists string[] Adblock Plus filter lists that :adblock-update downloads (https://, or file:// for local lists)

---@class rt.c.content.media
---@field audio_capture "ask"|"true"|"false" Let sites use your microphone: ask, true or false
---@field video_capture "ask"|"true"|"false" Let sites use your camera: ask, true or false

---@class rt.c.content.notifications
---@field enabled "ask"|"true"|"false" Let sites show notifications: ask, true or false

---@class rt.c.content.tls
---@field certificate_errors "ask"|"block"|"load-insecurely" Pages whose TLS certificate isn't trusted: ask, block, or load-insecurely

---@class rt.c.downloads
---@field location rt.c.downloads.location

---@class rt.c.downloads.location
---@field directory string Where downloads go; empty means the system Downloads folder
---@field prompt boolean Ask where to save each download (false saves straight to the directory)

---@class rt.c.editor
---@field command string[] Editor for :open-editor; fields: {file}, {line}, {column}, {line0}, {column0}

---@class rt.c.hints
---@field chars string Characters used for hint labels
---@field mode "letter"|"number" letter: labels from hints.chars; number: numbered labels, and typing letters filters by text
---@field uppercase boolean Show hint labels in upper case

---@class rt.c.input
---@field forward_unbound_keys "all"|"auto"|"none" Pass unbound keys to the page in normal mode (auto: all but plain letters and digits)
---@field insert_mode rt.c.input.insert_mode

---@class rt.c.input.insert_mode
---@field auto_enter boolean Enter insert mode when an editable element gets focus
---@field auto_leave boolean Leave insert mode when focus leaves an editable element
---@field leave_on_load boolean Leave insert mode when a new page starts loading

---@class rt.c.messages
---@field timeout integer Milliseconds before a status bar message clears (0 keeps it)

---@class rt.c.search
---@field ignore_case "smart"|"always"|"never" Case in searches: smart ignores it unless the text has a capital, always, or never
---@field incremental boolean Search while typing after / or ?

---@class rt.c.spellcheck
---@field languages string[] Spell-check languages such as en-US (empty: off); Chromium downloads each dictionary from Google once

---@class rt.c.statusbar
---@field position "top"|"bottom" Where the status bar is
---@field show "always"|"never"|"in-mode" When to show the status bar: always, only while typing a command or answering a prompt (never), or also outside normal mode and while a message is shown (in-mode)
---@field widgets string[] What the right side of the status bar shows, in order: keypress, downloads, muted, zoom, search_match, url, scroll, scroll_raw, history, tabs, progress, clock[:strftime format], text:…

---@class rt.c.tabs
---@field favicons rt.c.tabs.favicons
---@field last_close "ignore"|"blank"|"startpage"|"default-page"|"close" What closing the last tab does
---@field mode_on_change "normal"|"persist"|"restore" Mode after switching tabs: normal, persist (keep insert/passthrough), or restore (the mode the tab was left in)
---@field mousewheel_switching boolean Switch tabs with the mouse wheel over the tab bar
---@field new_position rt.c.tabs.new_position
---@field pinned rt.c.tabs.pinned
---@field position "top"|"bottom"|"left"|"right" Where the tab bar is; left and right list the tabs vertically
---@field show "always"|"never"|"multiple"|"switching" When to show the tab bar: always, never, with more than one tab, or briefly after switching tabs
---@field show_switching_delay integer How long the tab bar stays after switching tabs with tabs.show = switching, in milliseconds
---@field width integer Width of the tab bar in pixels when tabs.position is left or right

---@class rt.c.tabs.favicons
---@field show "always"|"never"|"pinned" Show site icons in the tab bar: always, never, or only on pinned tabs

---@class rt.c.tabs.new_position
---@field related "prev"|"next"|"first"|"last" Where tabs opened from a page go (popups, hints)
---@field unrelated "prev"|"next"|"first"|"last" Where other new tabs go (:open -t)

---@class rt.c.tabs.pinned
---@field frozen boolean Keep pinned tabs on their page: :open in a pinned tab opens a new tab
---@field shrink boolean Shrink pinned tabs to their icon and number

---@class rt.c.url
---@field default_page string Page for :open without a URL
---@field searchengines table<string, string> Search engines; ':open g rust' uses the 'g' entry, anything else DEFAULT
---@field start_pages string[] Pages opened at startup when no URL is given

---@class rt.c.window
---@field title_format string Window title; fields: {current_title}, {title_sep}, {current_url}, {host}, {mode}

---@class rt.c.zoom
---@field default integer Zoom in percent for pages, and what :zoom without a value resets to

---@type rt.c
c = {}
