//! Type definitions for lua-language-server, generated from the settings
//! registry so editors complete and check `c.*` and `hb.*` in config.lua.

use std::collections::BTreeMap;
use std::fmt::Write;

use hb_core::Mode;
use hb_core::settings::{Kind, SETTINGS, SettingDef};

#[derive(Default)]
struct Node {
    setting: Option<&'static SettingDef>,
    children: BTreeMap<String, Node>,
}

fn lua_type(kind: Kind) -> String {
    match kind {
        Kind::Bool => "boolean".into(),
        Kind::Int { .. } => "integer".into(),
        Kind::Str => "string".into(),
        Kind::Enum(options) => options
            .iter()
            .map(|o| format!("\"{o}\""))
            .collect::<Vec<_>>()
            .join("|"),
        Kind::List => "string[]".into(),
        Kind::Map => "table<string, string>".into(),
    }
}

fn class_name(path: &str) -> String {
    if path.is_empty() {
        "hb.c".into()
    } else {
        format!("hb.c.{path}")
    }
}

fn write_class(out: &mut String, path: &str, node: &Node) {
    let _ = writeln!(out, "---@class {}", class_name(path));
    for (name, child) in &node.children {
        let full = if path.is_empty() {
            name.clone()
        } else {
            format!("{path}.{name}")
        };
        match child.setting {
            Some(def) => {
                let _ = writeln!(
                    out,
                    "---@field {name} {} {}",
                    lua_type(def.kind),
                    def.description
                );
            }
            None => {
                let _ = writeln!(out, "---@field {name} {}", class_name(&full));
            }
        }
    }
    out.push('\n');
    for (name, child) in &node.children {
        if child.setting.is_none() {
            let full = if path.is_empty() {
                name.clone()
            } else {
                format!("{path}.{name}")
            };
            write_class(out, &full, child);
        }
    }
}

pub fn generate() -> String {
    let mut root = Node::default();
    for def in SETTINGS {
        let mut node = &mut root;
        for part in def.name.split('.') {
            node = node.children.entry(part.to_string()).or_default();
        }
        node.setting = Some(def);
    }

    let modes = Mode::ALL
        .iter()
        .map(|m| format!("\"{m}\""))
        .collect::<Vec<_>>()
        .join("|");
    let names = SETTINGS
        .iter()
        .map(|d| format!("\"{}\"", d.name))
        .collect::<Vec<_>>()
        .join("|");
    let mut out = String::new();
    let _ = write!(
        out,
        r#"---@meta
---@diagnostic disable: missing-fields
-- Type definitions for hackers-browser's config.lua, for lua-language-server.
-- Generated by `hackers-browser --lua-types`; do not edit.

---@alias hb.Mode {modes}
---@alias hb.SettingName {names}

---@class hb
---@field platform "linux"|"macos"|"windows"
---@field version string
---@field config_dir string
---@field data_dir string
hb = {{}}

---Set an option; `c.name = value` does the same. With `pattern` (e.g.
---`"*.example.com"` or `"https://meet.example.com"`), only for matching pages;
---this works for the content.* permission settings and content.blocking.enabled.
---@param name hb.SettingName
---@param value any
---@param pattern? string
function hb.set(name, value, pattern) end

---Get an option's current value.
---@param name hb.SettingName
---@return any
function hb.get(name) end

---Bind keys (qutebrowser notation, e.g. "<Ctrl-x>" or "gg") to a command,
---or to a Lua function that runs when they're pressed.
---@param keys string
---@param command string|fun()
---@param mode? hb.Mode defaults to "normal"
function hb.bind(keys, command, mode) end

---Remove a binding.
---@param keys string
---@param mode? hb.Mode defaults to "normal"
function hb.unbind(keys, mode) end

---Define a command, e.g. `:wiki rust`; `fn` gets the rest of the line.
---@param name string letters, digits, `-` and `_`
---@param fn fun(args: string)
---@param description? string shown in completion
function hb.command(name, fn, description) end

---Run `fn` on an event: "load_finished" and "url_changed" (`e.url`),
---"tab_opened" (`e.url`) or "mode_changed" (`e.from`, `e.to`).
---@param event "load_finished"|"url_changed"|"tab_opened"|"mode_changed"
---@param fn fun(e: table)
function hb.on(event, fn) end

---The current page's URL (in callbacks).
---@return string
function hb.url() end

---The current page's title (in callbacks).
---@return string
function hb.title() end

---The current mode, e.g. "normal" (in callbacks).
---@return string
function hb.mode() end

---The count typed before the key, if any (in callbacks).
---@return integer?
function hb.count() end

---Run a command line, e.g. `hb.run("tab-close")` (in callbacks).
---@param line string
function hb.run(line) end

---Open a URL (in callbacks).
---@param url string
---@param target? "current"|"tab"|"tab-bg"|"window"|"private"
function hb.open(url, target) end

---Show a message in the status bar (in callbacks).
---@param text string
---@param level? "info"|"error"
function hb.message(text, level) end

"#
    );
    write_class(&mut out, "", &root);
    out.push_str("---@type hb.c\nc = {}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const CHECKED_IN: &str = "../../docs/lua/hb.meta.lua";

    /// Regenerate with `UPDATE_LUA_TYPES=1 cargo test -p hb-config`.
    #[test]
    fn checked_in_types_are_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(CHECKED_IN);
        let generated = generate();
        if std::env::var_os("UPDATE_LUA_TYPES").is_some() {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &generated).unwrap();
        }
        // Git may check files out with CRLF line endings on Windows.
        let current = std::fs::read_to_string(&path)
            .unwrap_or_default()
            .replace("\r\n", "\n");
        assert!(
            current == generated,
            "docs/lua/hb.meta.lua is stale; run UPDATE_LUA_TYPES=1 cargo test -p hb-config"
        );
    }

    #[test]
    fn nests_settings_into_classes() {
        let types = generate();
        assert!(types.contains("---@field hints hb.c.hints\n"));
        assert!(types.contains("---@class hb.c.tabs.new_position\n"));
        assert!(types.contains("---@field last_close \"ignore\"|\"blank\"|"));
        assert!(types.contains("---@field start_pages string[] "));
    }
}

/// Markdown reference for every setting, checked in as docs/settings.md.
pub fn settings_markdown() -> String {
    let mut out = String::from(
        "# Settings\n\n<!-- Generated from crates/hb-core/src/settings.rs; regenerate with UPDATE_LUA_TYPES=1 cargo test -p hb-config. -->\n\n\
         Set these in `config.toml` (`hints.chars = \"asdf\"`), `config.lua` (`c.hints.chars = \"asdf\"`) or with `:set hints.chars asdf`.\n\n\
         | Setting | Type | Default | Description |\n|---|---|---|---|\n",
    );
    for def in SETTINGS {
        let kind = match def.kind {
            Kind::Enum(options) => options.join(" \\| "),
            other => lua_type(other).replace('|', "\\|"),
        };
        let default = def.default_value().to_string().replace('|', "\\|");
        let _ = writeln!(
            out,
            "| `{}` | {kind} | `{default}` | {} |",
            def.name, def.description
        );
    }
    out
}

#[cfg(test)]
mod docs_tests {
    #[test]
    fn checked_in_settings_doc_is_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/settings.md");
        let generated = super::settings_markdown();
        if std::env::var_os("UPDATE_LUA_TYPES").is_some() {
            std::fs::write(&path, &generated).unwrap();
        }
        // Git may check files out with CRLF line endings on Windows.
        let current = std::fs::read_to_string(&path)
            .unwrap_or_default()
            .replace("\r\n", "\n");
        assert!(
            current == generated,
            "docs/settings.md is stale; run UPDATE_LUA_TYPES=1 cargo test -p hb-config"
        );
    }
}
