//! Type definitions for lua-language-server, generated from the settings
//! registry so editors complete and check `c.*` and `rt.*` in config.lua.

use std::collections::BTreeMap;
use std::fmt::Write;

use rt_core::Mode;
use rt_core::settings::{Kind, SETTINGS, SettingDef};

#[derive(Default)]
struct Node {
    setting: Option<&'static SettingDef>,
    children: BTreeMap<String, Node>,
}

fn lua_type(kind: Kind) -> String {
    match kind {
        Kind::Bool => "boolean".into(),
        Kind::Int { .. } => "integer".into(),
        Kind::Str => "string".into(),
        Kind::Enum(options) => options
            .iter()
            .map(|o| format!("\"{o}\""))
            .collect::<Vec<_>>()
            .join("|"),
        Kind::List => "string[]".into(),
        Kind::Map => "table<string, string>".into(),
    }
}

fn class_name(path: &str) -> String {
    if path.is_empty() {
        "rt.c".into()
    } else {
        format!("rt.c.{path}")
    }
}

fn write_class(out: &mut String, path: &str, node: &Node) {
    let _ = writeln!(out, "---@class {}", class_name(path));
    for (name, child) in &node.children {
        let full = if path.is_empty() {
            name.clone()
        } else {
            format!("{path}.{name}")
        };
        match child.setting {
            Some(def) => {
                let _ = writeln!(
                    out,
                    "---@field {name} {} {}",
                    lua_type(def.kind),
                    def.description
                );
            }
            None => {
                let _ = writeln!(out, "---@field {name} {}", class_name(&full));
            }
        }
    }
    out.push('\n');
    for (name, child) in &node.children {
        if child.setting.is_none() {
            let full = if path.is_empty() {
                name.clone()
            } else {
                format!("{path}.{name}")
            };
            write_class(out, &full, child);
        }
    }
}

pub fn generate() -> String {
    let mut root = Node::default();
    for def in SETTINGS {
        let mut node = &mut root;
        for part in def.name.split('.') {
            node = node.children.entry(part.to_string()).or_default();
        }
        node.setting = Some(def);
    }

    let modes = Mode::ALL
        .iter()
        .map(|m| format!("\"{m}\""))
        .collect::<Vec<_>>()
        .join("|");
    let names = SETTINGS
        .iter()
        .map(|d| format!("\"{}\"", d.name))
        .collect::<Vec<_>>()
        .join("|");
    let events = crate::lua::EVENTS
        .iter()
        .map(|(name, _)| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join("|");
    let event_list: String = crate::lua::EVENTS
        .iter()
        .map(|(name, about)| format!("\n---- `{name}`: {about}"))
        .collect();
    let mut out = String::new();
    let _ = write!(
        out,
        r#"---@meta
---@diagnostic disable: missing-fields
-- Type definitions for riptide's config.lua, for lua-language-server.
-- Generated by `riptide --lua-types`; do not edit.

---@alias rt.Mode {modes}
---@alias rt.SettingName {names}
---@alias rt.Event {events}

---@class rt
---@field platform "linux"|"macos"|"windows"
---@field version string
---@field config_dir string
---@field data_dir string
rt = {{}}

---@deprecated `hb` is the old name of `rt`.
hb = rt

---Set an option; `c.name = value` does the same. With `pattern` (e.g.
---`"*.example.com"` or `"https://meet.example.com"`), only for matching pages;
---this works for the content.* permission settings and content.blocking.enabled.
---@param name rt.SettingName
---@param value any
---@param pattern? string
function rt.set(name, value, pattern) end

---Get an option's current value.
---@param name rt.SettingName
---@return any
function rt.get(name) end

---Define a theme for `ui.theme` and `:theme`, like a `themes/<name>.toml`
---file: `palette` holds base, surface, fg, accent, yellow, red, green and blue
---(and optionally surface2, surface3, muted, orange) as `#rrggbb`, and
---`colors` any `colors.*` setting without the `colors.` prefix.
---@param name string a-z, 0-9, `-` and `_`
---@param spec {{ palette: table<string, string>, colors?: table<string, string> }}
function rt.theme(name, spec) end

---Bind keys (qutebrowser notation, e.g. "<Ctrl-x>" or "gg") to a command,
---or to a Lua function that runs when they're pressed.
---@param keys string
---@param command string|fun()
---@param mode? rt.Mode defaults to "normal"
---@return string command what the keys run (`lua-call <n>` for a function)
function rt.bind(keys, command, mode) end

rt.keymap = {{}}

---Bind keys in one mode or several, as `vim.keymap.set`. `opts.desc` is shown
---in the key hints popup instead of the command.
---@param mode rt.Mode|rt.Mode[]
---@param keys string
---@param rhs string|fun()
---@param opts? {{ desc?: string }}
function rt.keymap.set(mode, keys, rhs, opts) end

---Remove a binding in one mode or several.
---@param mode rt.Mode|rt.Mode[]
---@param keys string
function rt.keymap.del(mode, keys) end

---Remove a binding.
---@param keys string
---@param mode? rt.Mode defaults to "normal"
function rt.unbind(keys, mode) end

---Define a command, e.g. `:wiki rust`; `fn` gets the rest of the line.
---`opts` is a description, or a table with `desc` and `complete`, a function
---that gets what's typed after the command and returns completions: strings,
---or `{{ name = "…", desc = "…" }}` tables.
---@param name string letters, digits, `-` and `_`
---@param fn fun(args: string)
---@param opts? string|{{ desc?: string, complete?: fun(arglead: string): (string|{{ name: string, desc?: string }})[] }}
function rt.command(name, fn, opts) end

---Run `fn` on an event, with a table of what it's about (`e.url`, …):{event_list}
---`opts.pattern` only runs it for matching pages (as `:set -u` patterns),
---`opts.group` names it for `rt.off`/`rt.group`, and `opts.once` runs it once.
---`rt.on(event, fn)` works too. Returns an id for `rt.off`.
---@param event rt.Event
---@param opts {{ pattern?: string, group?: string, once?: boolean }}|fun(e: table)
---@param fn? fun(e: table)
---@return integer
function rt.on(event, opts, fn) end

---Call `fn` once, `ms` milliseconds from now. `:stop()` on the result cancels it.
---@param ms integer
---@param fn fun()
---@return {{ stop: fun(self) }}
function rt.defer(ms, fn) end

---Call `fn` every `ms` milliseconds (10 or more) until `:stop()` is called on the result.
---@param ms integer
---@param fn fun()
---@return {{ stop: fun(self) }}
function rt.every(ms, fn) end

---Show a message in the status bar; the same as `rt.message`.
---@param text string
---@param level? "info"|"warning"|"error"
function rt.notify(text, level) end

---Data kept between runs under `name` (letters, digits, `-`, `_`), saved
---as JSON in the data folder on every change. Values are strings, numbers,
---booleans and tables of those.
---@param name string
---@return {{ get: fun(key: string): any, set: fun(key: string, value: any), all: fun(): table, clear: fun() }}
function rt.store(name) end

---@class rt.PluginSpec
---@field [1]? string A git URL, the same as `src`.
---@field src? string A git URL to install it from.
---@field dir? string A folder on your computer instead.
---@field builtin? string A plugin that ships with riptide, e.g. "passwords".
---@field name? string Its name for `require`; by default from the URL or folder.
---@field version? string A tag, branch or commit.
---@field trusted? boolean Skip the sandbox and allow everything.
---@field opts? table Passed to `require(name).setup(opts)` once it loads.
---@field config? fun() Run once it loads, instead of `opts`.
---@field event? rt.Event|rt.Event[] Load when one of these events fires.
---@field cmd? string|string[] Load when one of these commands runs.
---@field keys? string|(string|{{ [1]: string, mode?: string }})[] Load when one of these keys is pressed.

rt.statusbar = {{}}

---A status bar widget: `fn` gives its text each time the bar is drawn,
---where `statusbar.widgets` lists `"lua:<name>"`. It gets 50 ms; one that
---fails or runs longer is removed. `nil` instead of `fn` removes it.
---@param name string Letters, digits, `-` and `_`.
---@param fn? fun(): string|number|nil
function rt.statusbar.widget(name, fn) end

rt.pack = {{}}

---Add plugins: a git URL, a spec, or a list of them. They load once
---`config.lua` has run, or with `event`, `cmd` or `keys` only when needed.
---@param specs string|rt.PluginSpec|(string|rt.PluginSpec)[]
function rt.pack.add(specs) end

---Remove a hook by the id `rt.on` returned, or every hook in a group.
---@param id integer|string
function rt.off(id) end

---A group name for hooks; `{{ clear = true }}` first removes the group's
---hooks, so a script that runs again doesn't add them twice.
---@param name string
---@param opts? {{ clear?: boolean }}
---@return string
function rt.group(name, opts) end

---The current page's URL (in callbacks).
---@return string
function rt.url() end

---The current page's title (in callbacks).
---@return string
function rt.title() end

---The current mode, e.g. "normal" (in callbacks).
---@return string
function rt.mode() end

---The current window's tabs, in order (in callbacks).
---@return {{ index: integer, title: string, url: string, current: boolean, pinned: boolean }}[]
function rt.tabs() end

---The count typed before the key, if any (in callbacks).
---@return integer?
function rt.count() end

---Run a command line, e.g. `rt.run("tab-close")` (in callbacks).
---@param line string
function rt.run(line) end

---Open a URL (in callbacks).
---@param url string
---@param target? "current"|"tab"|"tab-bg"|"window"|"private"
function rt.open(url, target) end

---Show a message in the status bar (in callbacks).
---@param text string
---@param level? "info"|"warning"|"error"
function rt.message(text, level) end

---@class rt.SpawnOpts
---@field stdin? string written to the program's standard input
---@field cwd? string the directory to run it in
---@field env? table<string, string> extra environment variables

---@class rt.SpawnResult
---@field code integer|nil the exit code; nil if a signal ended it or it didn't start
---@field stdout string
---@field stderr string
---@field error string|nil why it couldn't run

---Run a program in the background (in callbacks); no shell is involved.
---`argv` is a list, or a command line split like `:spawn` does.
---@param argv string[]|string
---@param opts? rt.SpawnOpts|fun(result: rt.SpawnResult)
---@param callback? fun(result: rt.SpawnResult) called when it exits
function rt.spawn(argv, opts, callback) end

rt.ui = {{}}

---@class rt.SelectOpts
---@field prompt? string the question shown above the items
---@field format? fun(item: any): string how to show an item; tostring by default

---Pick one of `items` in the prompt area, like `vim.ui.select`: each item has
---a key (1-9, then a-z; at most 35 items), and Return picks the first.
---`on_choice` gets the item and its index, or nil when cancelled.
---@param items any[]
---@param opts? rt.SelectOpts
---@param on_choice fun(item: any|nil, index: integer|nil)
function rt.ui.select(items, opts, on_choice) end

---@class rt.InputOpts
---@field prompt? string the question
---@field default? string text to start with
---@field secret? boolean mask what's typed, for passwords

---Ask for text in the prompt area, like `vim.ui.input`. `on_confirm` gets
---the text, or nil when cancelled.
---@param opts? rt.InputOpts
---@param on_confirm fun(text: string|nil)
function rt.ui.input(opts, on_confirm) end

---@alias rt.Highlight "title"|"muted"|"accent"|"match"|"url"|"key"|"info"|"warning"|"error"

---@class rt.FloatOpts
---@field title? string
---@field lines? (string|(string|{{ [1]: string, [2]: rt.Highlight }})[])[] Text, or chunks of text with highlights; never HTML.
---@field width? integer The widest it gets, in characters (10–200, default 60).
---@field position? "center"|"top"|"bottom"|"top-right"|"bottom-right"
---@field timeout? integer Close by itself after this many milliseconds.
---@field keys? table<string, fun(float: rt.Float)> Keys it takes in normal mode while it's the newest float with keys; Escape closes it.
---@field on_close? fun() Called when riptide closes it (Escape, its timeout).

---@class rt.Float
---@field id integer
local Float = {{}}
---Redraw with these options changed.
---@param changes rt.FloatOpts
function Float:update(changes) end
function Float:close() end
---@return boolean
function Float:is_open() end

---A box of text over the page. A plugin's floats show its name.
---@param opts rt.FloatOpts
---@return rt.Float
function rt.ui.float(opts) end

---@class rt.PanelOpts
---@field title? string
---@field lines? (string|(string|{{ [1]: string, [2]: rt.Highlight }})[])[] Text, or chunks of text with highlights; never HTML.
---@field side? "left"|"right"|"bottom" Default left.
---@field size? integer Width beside the page, or height below it, in pixels (default 300, or 200 below).
---@field keys? table<string, fun(panel: rt.Panel, line: integer)> Keys it takes while focused, with the cursor's line; j/k move the cursor and Escape returns to the page.
---@field on_close? fun() Called when riptide closes it (its window closing, another panel taking its side).

---@class rt.Panel
---@field id integer
local Panel = {{}}
---Redraw with these options changed.
---@param changes rt.PanelOpts
function Panel:update(changes) end
function Panel:close() end
---Give it the keyboard until Escape.
function Panel:focus() end
---@return boolean
function Panel:is_open() end

---@class rt.PageOpts
---@field path? string A file in the plugin's `pages/` folder (default `index.html`).
---@field where? "tab"|"panel" Default tab.
---@field side? "left"|"right"|"bottom" In a panel; default right.
---@field size? integer In a panel: its width, or height below the page, in pixels (default 400).
---@field on_message? fun(name: string, data: any, page: rt.Page) A message the page sent with `rt.send(name, json)`.

---@class rt.Page
---@field id integer
local Page = {{}}
---Send the page a message: it gets an `rtmessage` event with `detail.name` and `detail.data`.
---@param name string
---@param data any Anything `rt.json.encode` takes.
function Page:send(name, data) end
---Close its panel, or the tabs showing it.
function Page:close() end

---Open one of this plugin's pages in a tab or a panel. Only plugins have pages.
---@param opts? rt.PageOpts
---@return rt.Page
function rt.ui.page(opts) end

---Lines beside or below the page, one panel per side of a window. A plugin's panels show its name.
---@param opts rt.PanelOpts
---@return rt.Panel
function rt.ui.panel(opts) end

---The current tab's page. Plugins need the `pages` permission for the site,
---checked when the action runs; nothing acts on riptide's own pages, and what's
---typed or filled is never logged or kept in history.
rt.page = {{}}

---Type text into the focused field, as `:insert-text` does.
---@param text string
function rt.page.type(text) end

---Press keys in the page, as `:fake-key` does, e.g. `"<Tab>"`.
---@param keys string
function rt.page.key(keys) end

---@class rt.Login
---@field host string the site the login is for; nothing is filled if the tab has moved on to another
---@field username? string
---@field password? string
---@field submit? boolean submit the form once it's filled

---Fill the page's login form: the focused field's form, or the first with a
---password field.
---@param login rt.Login
function rt.page.fill_login(login) end

---Evaluate a JavaScript expression in the page and get its value, as JSON
---turns it into Lua: `fn(value)`, or `fn(nil, why)`. It runs in the page's
---own world, so the page can see it and change what it returns.
---@param code string An expression; wrap statements in `(() => {{ … }})()`.
---@param fn fun(value: any, err: string|nil)
function rt.page.eval(code, fn) end

---Add a stylesheet to the page, until it next loads.
---@param css string
function rt.page.css(css) end

---The page's selected text: `fn(text)`, or `fn(nil, why)`.
---@param fn fun(text: string|nil, err: string|nil)
function rt.page.selection(fn) end

---@class rt.HintedElement
---@field url string|nil Its link, if it has one.
---@field text string Its text, lowercased.

---Hint the elements `selector` matches, in frames of sites the plugin may act
---on, and hand the one you pick to `action`; nothing is clicked.
---@param opts {{ selector: string, action: fun(element: rt.HintedElement|nil, err: string|nil) }}
function rt.page.hint(opts) end

rt.json = {{}}

---Parse JSON; `null` becomes nil.
---@param text string
---@return any
function rt.json.decode(text) end

---Write a value as JSON.
---@param value any
---@return string
function rt.json.encode(value) end

"#
    );
    write_class(&mut out, "", &root);
    out.push_str("---@type rt.c\nc = {}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const CHECKED_IN: &str = "../../docs/lua/rt.meta.lua";

    /// Regenerate with `UPDATE_LUA_TYPES=1 cargo test -p rt-config`.
    #[test]
    fn checked_in_types_are_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(CHECKED_IN);
        let generated = generate();
        if std::env::var_os("UPDATE_LUA_TYPES").is_some() {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &generated).unwrap();
        }
        // Git may check files out with CRLF line endings on Windows.
        let current = std::fs::read_to_string(&path)
            .unwrap_or_default()
            .replace("\r\n", "\n");
        assert!(
            current == generated,
            "docs/lua/rt.meta.lua is stale; run UPDATE_LUA_TYPES=1 cargo test -p rt-config"
        );
    }

    #[test]
    fn nests_settings_into_classes() {
        let types = generate();
        assert!(types.contains("---@field hints rt.c.hints\n"));
        assert!(types.contains("---@class rt.c.tabs.new_position\n"));
        assert!(types.contains("---@field last_close \"ignore\"|\"blank\"|"));
        assert!(types.contains("---@field start_pages string[] "));
    }
}

/// Markdown reference for every setting, checked in as docs/settings.md.
pub fn settings_markdown() -> String {
    let mut out = String::from(
        "# Settings\n\n<!-- Generated from crates/rt-core/src/settings.rs; regenerate with UPDATE_LUA_TYPES=1 cargo test -p rt-config. -->\n\n\
         Set these in `config.toml` (`hints.chars = \"asdf\"`), `config.lua` (`c.hints.chars = \"asdf\"`) or with `:set hints.chars asdf`.\n\n\
         | Setting | Type | Default | Description |\n|---|---|---|---|\n",
    );
    for def in SETTINGS {
        let kind = match def.kind {
            Kind::Enum(options) => options.join(" \\| "),
            other => lua_type(other).replace('|', "\\|"),
        };
        let default = def.default_value().to_string().replace('|', "\\|");
        let _ = writeln!(
            out,
            "| `{}` | {kind} | `{default}` | {} |",
            def.name, def.description
        );
    }
    out
}

#[cfg(test)]
mod docs_tests {
    #[test]
    fn checked_in_settings_doc_is_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs/settings.md");
        let generated = super::settings_markdown();
        if std::env::var_os("UPDATE_LUA_TYPES").is_some() {
            std::fs::write(&path, &generated).unwrap();
        }
        // Git may check files out with CRLF line endings on Windows.
        let current = std::fs::read_to_string(&path)
            .unwrap_or_default()
            .replace("\r\n", "\n");
        assert!(
            current == generated,
            "docs/settings.md is stale; run UPDATE_LUA_TYPES=1 cargo test -p rt-config"
        );
    }
}
