[package]
name = "hb"
description = "hackers-browser: a vim-like browser on CEF"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hackers-browser"
path = "src/main.rs"

[features]
sandbox = ["hb-cef/sandbox"]

[dependencies]
hb-cef.workspace = true
tracing-subscriber.workspace = true
